config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers=> {registration:'registration'}
  root 'site#index'

  get 'privacy' => 'site#privacy'
  get 'terms'   =>  'site#terms'
  get 'meal_plans'=> 'site#meal_plans'
  get 'login'=> "site#Login"
  get 'mothers_plan' => 'site#mothers_plan'
  get 'lifestyle_plan'=> 'site#lifestyle_plan'
  get 'athletes_Plan'=> 'site#athletes_Plan'
  get 'sign_up'=> 'site#sign_up'
  get 'sign_in'=> 'site#sign_in'
  get 'contact_us'=> 'site#Contact_us'
  post 'contact' => 'contacts#create'
  # post 'like' => 'Recipes#like'




  # routes for URL
  post 'url'  =>'url#create'
  get  'url'  =>'url#index'
  get 'sign_up'=> 'site#sign_up'
  get 'sign_in'=> 'site#sign_in'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  validates :message, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/url.rb
class Url < ActiveRecord::Base
  before_save :check_url_http

  validate :check_com

  def check_url_http
    self.original = 'http://' + self.original
  end

  def check_com
    unless self.original.include? ".com"
      self.errors.add :base, "the original URL should contain.com"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/URL_Controller.rb
class UrlController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    url= Url.new
    url.original = params[:url]

    if url.save
      render :create
    else
      #where to go
      render :text => "Error"
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < Application

  def accounts

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  protect_from_forgery with: :null_session

  def new
  end

  def create
    @contact = Contact.new
    @contact.name = params[:first_name]
    @contact.email = params[:email]
    @contact.subject = 'New Contact'
    @contact.message = params[:comments]

    if @contact.save
      # send email
      UserMailer.contact_us_email(@contact).deliver

    else
      flash.now[:alert] = 'There is an error'
    end
  end

end

app/controllers/menu controllers.rb
class MenuControllers < ApplicationController

  def receipe

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def create

  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

  def meal_plans
  end

  def mothers_plan
  end

  def Lifestyle_plan
  end

  def Athletes_Plan
  end

  def Contact_Us
  end

  def sign_up
  end

  def sign_in
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_noty_script_tag
    unless flash.empty?
      noties = flash.map do |name, message|
        if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
          type = ( name == :notice ? "success" : "error" )
          timeout = ( name == :notice ? 4000 : 30000 )
          text = ( message.is_a?(ActiveModel::Errors) ? "It's an error object" : message )

          "noty({ layout: 'top', type: '" + type +
          "', timeout: " + timeout.to_s +
          ", text: \"" + text +
          "\"});"
        end
      end

      javascript_tag( "$(function() {\n  " + noties.join("\n  ") + "\n});")
    end
  end

  def nav_link(link_text, link_path, link_class='')
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

end

app/views/layouts/_messages.html.erb
<%
flash.each do |name, message|
  if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
    notyType = (name == :notice ? "success" : "error")
    notyTimeout = (name == :notice ? 4000 : 30000)

    if message.is_a?(ActiveModel::Errors)
      notyText = "It's an error object"
    else
      notyText = message
    end
  end
%>

<%= javascript_tag do %>
    $(function() {
      noty({
        layout: 'top',
        type: "<%= notyType %>",
        timeout: "<%= notyTimeout %>",
        text: "<%= notyText %>"
      });
    });
<% end %>
<%
end
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fresh Meals</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
<!-- <form id= "loginForm">
  <input type="button" value= 'login'>
</form>
<form id= "createAccountForm">
  <input type="button" value='create account'>
</form> -->

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Fresh Meals</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= nav_link 'Home', root_path %></li>
          <li><%= nav_link 'Meal Plans', meal_plans_path %></li>
          <li><%= nav_link 'Contact Us', contact_us_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>Logged in as <strong><%= current_user.email %></strong>.</li>
            <li><%= nav_link 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% else %>
            <li><%= nav_link "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= nav_link "Login", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>


  <div class="container">

    <div class="starter-template">
      <h1></h1>

    </div>

    <%= yield %>

  </div>

<%= flash_noty_script_tag %>

</body>
</html>